### ISSUE TITLE
新增加指纹有问题

### ISSUE THREAD

**Issue by luotext** [ZuoHailong/BiometricPrompt#2]
新增加指纹后，指纹解锁直接报错了。
java.lang.IllegalStateException: Crypto primitive not initialized
        at android.security.keystore.AndroidKeyStoreProvider.getKeyStoreOperationHandle(AndroidKeyStoreProvider.java:163)
        at android.hardware.fingerprint.FingerprintManager$CryptoObject.getOpId(FingerprintManager.java:344)
        at android.hardware.fingerprint.FingerprintManager.authenticate(FingerprintManager.java:629)
        at android.hardware.fingerprint.FingerprintManager.authenticate(FingerprintManager.java:575)
        at androidx.core.hardware.fingerprint.FingerprintManagerCompat.authenticate(FingerprintManagerCompat.java:110)
        at com.hailong.biometrics.fingerprint.FingerprintImplForAndrM.authenticate(FingerprintImplForAndrM.java:50)
        at com.hailong.biometrics.fingerprint.FingerprintVerifyManager.<init>(FingerprintVerifyManager.java:49)
        at com.hailong.biometrics.fingerprint.FingerprintVerifyManager$Builder.build(FingerprintVerifyManager.java:188)
        at com.hailong.biometrics.fingerprint.example.FingerDemoActivity.fingerprint(FingerDemoActivity.java:35)
        at com.hailong.biometrics.fingerprint.example.FingerDemoActivity.lambda$onCreate$0(FingerDemoActivity.java:27)
        at com.hailong.biometrics.fingerprint.example.-$$Lambda$FingerDemoActivity$dyzlIM1OY_wIJS0vrZCfGfP7k3g.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:6390)
        at android.view.View$PerformClick.run(View.java:25270)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:187)
        at android.app.ActivityThread.main(ActivityThread.java:7025)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)

**Comment by ZuoHailong** [comment]
谢谢反馈，1.0版本已修复此bug。
